export const MBA_ACCORDION_YEARS = [
  {
    yearLabel: "YEAR 1",
    phaseLabel: "DESIGN",
    phaseNote: "(Design your learning path)",
    semesters: [
      [
        "Business Foundation Core 1",
        "Business Foundation Core 2",
        "Business Foundation Core 3",
        "Proficiency Core 1",
        "Professional Skills 1",
        "Professional Skills 2",
        "Proficiency Core 2",
        "University Core 1 (Value-Based)",
        "Sports & Wellness 1",
        "Open Elective 1 (Multi Disciplinary)",
      ],
      [
        "Business Foundation Core 4",
        "Business Foundation Core 5",
        "Business Foundation Core 6",
        "Proficiency Core 2",
        "Professional Skills 3",
        "University Core 2 (Value-Based)",
        "Sports & Wellness 2",
        "Open Elective 2 (Multi Disciplinary)",
        "University Core 3 (Value-Based)",
      ],
    ],
  },
  {
    yearLabel: "YEAR 2",
    phaseLabel: "EXPLORE",
    phaseNote: "(Go beyond boundaries. Dive deeper. Learn by doing!)",
    semesters: [
      [
        "Business Foundation Core 7",
        "Business Foundation Core 8",
        "Major Core 1",
        "Major Core 2",
        "Professional Skills 4",
        "University Core 4 (Value-Based)",
        "Sports & Wellness 3",
        "Open Elective 3 (Multi Disciplinary)",
        "Industry Integrated Learning 1",
      ],
      [
        "Business Foundation Core 9",
        "Business Foundation Core 10",
        "Program Basic 11",
        "Major Core 3",
        "Major Core 4",
        "Minor 1*",
        "Minor 2*",
        "Professional Skills 5",
        "Sports & Wellness 4",
        "University Core 5 (Value-Based)",
      ],
    ],
  },
  {
    yearLabel: "YEAR 3",
    phaseLabel: "EMBRACE",
    phaseNote:
      "(Own your journey. Embrace leadership, step into your purpose!)",
    semesters: [
      [
        "Business Foundation Core 12",
        "Business Foundation Core 13",
        "Major Elective 1",
        "Major Elective 2",
        "Major Elective 3",
        "Minor 4*",
        "Professional Skills 6",
        "Sports & Wellness 5",
      ],
      [
        "Business Foundation Core 14",
        "Major Elective 4",
        "Minor 5*",
        "Minor 6*",
        "Professional Skills 7",
        "Sports & Wellness 6",
        "Industry integrated learning 2",
      ],
    ],
  },
  {
    yearLabel: "YEAR 4",
    phaseLabel: "ELEVATE",
    phaseNote: "(Rise to Mastery)",
    semesters: [
      [
        "Advanced Major Elective 1",
        "Advanced Major Elective 2",
        "Advanced Minor Elective 1",
        "Quantitative & Qualitative Research Methods",
        "Field Study/Minor Research Project",
      ],
      [
        "Advanced Major Elective 3",
        "Advanced Minor Elective 2",
        "Dissertation/Capstone Project",
      ],
    ],
  },
]
